<?php
$sql = "CREATE TABLE patient (
    pID INT(11) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    pFname VARCHAR(255) NOT NULL,
    pMname VARCHAR(255) NOT NULL,
    pLname VARCHAR(255) NOT NULL,
    pSuffix VARCHAR(255) NOT NULL,
    pAddress VARCHAR(255) NOT NULL,
    pBdate DATE NOT NULL,
    pContact VARCHAR(255) NOT NULL UNIQUE,
    pUsername VARCHAR(255) NOT NULL UNIQUE,
    pPass VARCHAR(255) NOT NULL,
    pConfirm VARCHAR(255) NOT NULL,
    pCdate DATE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    pModified VARCHAR(255) NOT NULL
)";
